### ISSUE TITLE
Minimap closes source file .css

### ISSUE THREAD

**Issue by surfmk** [mcheung63/netbeans-minimap#13]
Hi,
I'm having an issue where I have to deactivate minimap for the moment as it closes a style.css file as soon as I try to open it.
I traced it to the base64 (long lines of text) that it doesn't like.
If you want the file it crashes on, please email me at surfmk@hotmail.co.uk
Thanks,
Paul.

**Comment by mcheung63** [comment]
Confirmed your css file will crash minimap, thanks. And the error is heap space error, that means minimap used too much memory. Let's me think how to fix it, give me some more time, thanks
<img width="1680" alt="screen shot 2017-09-26 at 3 42 40 pm" src="https://user-images.githubusercontent.com/1779905/30857367-04ba04b8-a2ee-11e7-845b-906f867a53d4.png">

**Comment by mcheung63** [comment]
In your css, line 420 is just too long, so minimap need to generate a very very large image for render, so it eats up all memory and cause the error. Two ways to fix it: 1) split the line into shorter line 2) allocate more memory to netbeans by edit netbeans.conf change "-J-Xmx8192m" to larger value. I changed from 4096m to 8192m and the error disappear.

If minimap is too lag, set this value to lower, see below
<img width="439" alt="screen shot 2017-09-26 at 7 13 18 pm" src="https://user-images.githubusercontent.com/1779905/30857726-71c4b372-a2ef-11e7-8b2e-883281c3a7d8.png">


Second, because the longest line is just too long than the average line length, so nothing you can see on minimap except those few longest lines. Please set the scale to higher value so the minimap become meaningful. See below
<img width="435" alt="screen shot 2017-09-26 at 7 13 42 pm" src="https://user-images.githubusercontent.com/1779905/30857739-7a4a2c2a-a2ef-11e7-9f4c-19118c64534d.png">
![Uploading Screen Shot 2017-09-26 at 7.12.23 PM.png…]()

**Comment by surfmk** [comment]
Thanks Peter,

I’ll check when I get home… I can see that a very long base64 string might be a challenge for mini-map.

Will make the changes you suggest – I’m not sure if splitting the lines is allowed in css?  I know that html ignores carriage returns but not sure about css.

Will confirm working later tonight.

Best regards,

Paul Davey
E: surfmk@hotmail.co.uk<mailto:surfmk@hotmail.co.uk>
T: +44 (0)1273 424131
M: +44 (0)7900 496417

**Comment by mcheung63** [comment]
I am going to enhance minimap in this way. If i found a few lines which is much much longer than the average, i cut it myself.

**Comment by surfmk** [comment]
Good plan – thanks for your help.

Paul Davey
E: surfmk@hotmail.co.uk<mailto:surfmk@hotmail.co.uk>
T: +44 (0)1273 424131
M: +44 (0)7900 496417

**Comment by surfmk** [comment]
Hi Peter,

Did you make this adjustment to MiniMap, so it automatically ignores very long text?

I will try the 2 suggestions you made later today but wondering if you have updated the main plugin so I just need to install the new plugin?

Thanks,

Paul Davey
E: surfmk@hotmail.co.uk<mailto:surfmk@hotmail.co.uk>
T: +44 (0)1273 424131
M: +44 (0)7900 496417

**Comment by mcheung63** [comment]
i promise i upload to plugin central tomorrow night :-)

Thanks
From Peter

surfmk <notifications@github.com<mailto:notifications@github.com>> 於 2017年9月30日 下午6:23 寫道：

Hi Peter,

Did you make this adjustment to MiniMap, so it automatically ignores very long text?

I will try the 2 suggestions you made later today but wondering if you have updated the main plugin so I just need to install the new plugin?

Thanks,

Paul Davey
E: surfmk@hotmail.co.uk<mailto:surfmk@hotmail.co.uk><mailto:surfmk@hotmail.co.uk>
T: +44 (0)1273 424131
M: +44 (0)7900 496417

**Comment by surfmk** [comment]
Great !

I might just wait until then – I have some InDesign work today.

Best regards,

Paul Davey
E: surfmk@hotmail.co.uk<mailto:surfmk@hotmail.co.uk>
T: +44 (0)1273 424131
M: +44 (0)7900 496417

**Comment by mcheung63** [comment]
Done, now i set the ratio to 10 times, that mean the longest line can only <= average line length * 10, otherwise i trim it. Now opening your css file is quick not don't crash. Uploaded to plugin central, you wait a few days then it will become available, version is 3.3, Thanks

![untitled](https://user-images.githubusercontent.com/1779905/31055156-2d0551fe-a6f2-11e7-9921-aabf73b557bc.png)

**Comment by surfmk** [comment]
Thanks Peter,

That’s fantastic… I keep trying other IDEs but still like Netbeans (hard to explain), so I really appreciate you helping with this bug.

Best regards,

Paul Davey

**Comment by surfmk** [comment]
Confirmed all working with 3.3 – thanks again for your efforts.

Paul.
